### ISSUE TITLE
Font not included for particular PDF - invisible output text

### ISSUE THREAD

**Issue by ViliusSutkus89** [ViliusSutkus89/pdf2htmlEX-Android#8]
[sample.pdf](https://github.com/ViliusSutkus89/pdf2htmlEX-Android/files/3903532/sample.pdf)

Produces
```CSS
.ff1{font-family:sans-serif;visibility:hidden;}
```
Instead of
```CSS
@font-face{font-family:ff1;src:url('data:application/font-woff;base64,---LONG-LONG-BASE64-ENCODED-STRING----=')format("woff");}.ff1{font-family:ff1;line-height:1.283203;font-style:normal;font-weight:normal;visibility:visible;}
```
